workspace '../Objective-LevelDB'
inhibit_all_warnings!

if ENV["TEST_ENV"] == "OSX"
  xcodeproj 'Objective-LevelDB OS X Tests'
  target :'OS X Tests' do
    platform :osx, '10.9'
  end
else
  xcodeproj 'Objective-LevelDB iOS Tests'
  target :'iOS Tests' do
    platform :ios, '7.0'
  end
end
